from rest_framework import serializers

class ProductFamilySerializer(serializers.Serializer):
    id = serializers.SerializerMethodField()
    category = serializers.CharField(max_length=100)
    name = serializers.CharField(max_length=255)
    description = serializers.CharField(max_length=500, required=False, allow_blank=True)
    default_items = serializers.JSONField(binary=False)
    base_margin = serializers.DecimalField(max_digits=5, decimal_places=2, required=False, default=0.00)

    def get_id(self, obj):
        print(obj)
        sk = obj.get('SK', '')
        try:
            return sk.split('#')[-1]
        except IndexError:
            return None

class MasterItemSerializer(serializers.Serializer):
    id = serializers.SerializerMethodField() # Will be generated by service
    category = serializers.CharField(max_length=100) # e.g., MATERIAL, LABOR
    name = serializers.CharField(max_length=255)
    unit_price = serializers.DecimalField(max_digits=10, decimal_places=2)
    unit_type = serializers.CharField(max_length=50) # e.g., sqft, unit, hour

    def get_id(self, obj):
        sk = obj.get('SK', '')
        try:
            return sk.split('#')[-1]
        except IndexError:
            return None

class ProductSerializer(serializers.Serializer):
    id = serializers.SerializerMethodField()
    name = serializers.CharField(max_length=255)
    description = serializers.CharField(required=False, allow_blank=True)
    price = serializers.DecimalField(max_digits=10, decimal_places=2)
    family_id = serializers.UUIDField(required=False, allow_null=True)

    def get_id(self, obj):
        sk = obj.get('SK', '')
        try:
            return sk.split('#')[-1]
        except IndexError:
            return None
    