AWSTemplateFormatVersion: '2010-09-09'
Description: Infrastructure for Quotely Application

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  
  ExistingTableName:
    Type: String
    Default: QuotelyCore
    Description: Name of the existing DynamoDB table
  
  ExistingBucketName:
    Type: String
    Default: quotely-quotes
    Description: Name of the existing S3 bucket (or name to create)  
    ExistingBucketName:
  
      Type: String
  
      Default: quotely-quotes
  
      Description: Name of the existing S3 bucket (or name to create)
  
  
  
    EcrRepositoryArn:
  
      Type: String
  
      Description: ARN of the ECR repository
  
  
  
  Resources:
  
    # -------------------------------------------------------------------------
  
    # DynamoDB Table
  
    # -------------------------------------------------------------------------
  
    QuotelyTable:
  
      Type: AWS::DynamoDB::Table
  
      Properties:
  
        TableName: !Ref ExistingTableName
  
        BillingMode: PAY_PER_REQUEST
  
        AttributeDefinitions:
  
          - AttributeName: PK
  
            AttributeType: S
  
          - AttributeName: SK
  
            AttributeType: S
  
        KeySchema:
  
          - AttributeName: PK
  
            KeyType: HASH
  
          - AttributeName: SK
  
            KeyType: RANGE
  
  
  
    # -------------------------------------------------------------------------
  
    # S3 Bucket
  
    # -------------------------------------------------------------------------
  
    QuotelyBucket:
  
      Type: AWS::S3::Bucket
  
      Properties:
  
        BucketName: !Ref ExistingBucketName
  
        
  
    # -------------------------------------------------------------------------
  
    # ECR Repository
  
    # -------------------------------------------------------------------------
  
    QuotelyRepository:
  
      Type: AWS::ECR::Repository
  
      Properties:
  
        RepositoryName: "quotely-serverless"
  
  
  
    # -------------------------------------------------------------------------
  
    # IAM Role for Lambda
  
    # -------------------------------------------------------------------------
  
    LambdaExecutionRole:
  
      Type: AWS::IAM::Role
  
      Properties:
  
        RoleName: !Sub "quotely-api-role-${Environment}"
  
        AssumeRolePolicyDocument:
  
          Version: '2012-10-17'
  
          Statement:
  
            - Effect: Allow
  
              Principal:
  
                Service: lambda.amazonaws.com
  
              Action: sts:AssumeRole
  
        ManagedPolicyArns:
  
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  
        Policies:
  
          - PolicyName: ECRImageAccess
  
            PolicyDocument:
  
              Version: '2012-10-17'
  
              Statement:
  
                - Effect: Allow
  
                  Action:
  
                    - ecr:GetDownloadUrlForLayer
  
                    - ecr:BatchGetImage
  
                    - ecr:BatchCheckLayerAvailability
  
                  Resource: !Ref EcrRepositoryArn
  
          - PolicyName: QuotelyDataAccess
  
            PolicyDocument:
  
              Version: '2012-10-17'
  
              Statement:
  
                - Effect: Allow
  
                  Action:
  
                    - dynamodb:GetItem
  
                    - dynamodb:PutItem
  
                    - dynamodb:UpdateItem
  
                    - dynamodb:DeleteItem
  
                    - dynamodb:Query
  
                    - dynamodb:Scan
  
                    - dynamodb:BatchWriteItem
  
                  Resource: 
  
                    - !GetAtt QuotelyTable.Arn
  
                    - !Sub "${QuotelyTable.Arn}/index/*"
  
                - Effect: Allow
  
                  Action:
  
                    - s3:GetObject
  
                    - s3:PutObject
  
                    - s3:DeleteObject
  
                    - s3:GeneratePresignedUrl # Added for consistency, it was there earlier
  
                  Resource: 
  
                    - !Sub "${QuotelyBucket.Arn}/*"
  
  