AWSTemplateFormatVersion: '2010-09-09'
Description: Infrastructure for Quotely Application

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  
  ExistingTableName:
    Type: String
    Default: QuotelyCore-v6
    Description: Name of the existing DynamoDB table

Resources:
  # -------------------------------------------------------------------------
  # DynamoDB Table
  # -------------------------------------------------------------------------
  QuotelyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref ExistingTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE