AWSTemplateFormatVersion: '2010-09-09'
Description: Infrastructure for Quotely Application

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  
  ExistingTableName:
    Type: String
    Default: QuotelyCore
    Description: Name of the existing DynamoDB table
  
  ExistingBucketName:
    Type: String
    Default: quotely-quotes
    Description: Name of the existing S3 bucket (or name to create)

Resources:
  # -------------------------------------------------------------------------
  # DynamoDB Table
  # -------------------------------------------------------------------------
  QuotelyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref ExistingTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  # -------------------------------------------------------------------------
  # S3 Bucket
  # -------------------------------------------------------------------------
  QuotelyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ExistingBucketName